version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    env_file: .env
    links:
      - mysql
      - redis
      - rabbitmq 
      - jenkins
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
      MYSQL_DATABASE: platform
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis"
    volumes:
      - redis_data:/var/lib/redis

  rabbitmq:
    image: "rabbitmq"

  adminer:
    image: adminer
    ports:
      - "8090:8080"

  jenkins:
    image: "jenkinsci/blueocean"
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data:
  mysql_data:
  jenkins_data:
